task:
  scheduling:
    pool:
      size: 2
spring:
  elasticsearch:
    uris: http://elasticsearch:9200
yellow-collector:
  sr-processor:
    runners:
      fixed-delay-in-milliseconds: 5000
      initial-delay-in-milliseconds: 10000
      worker-pool-size: 5
      size-of-report-processing-queue: 100
      timeout-on-report-processing-iteration-in-minutes: 5
    storage:
      temp: /var/yellow-processor/temp
      root: /var/yellow-processor/root
      error: /var/yellow-processor/error
    rotation:
      root-location-in-days: 2
      error-location-in-days: 2
      purge-reports-cron: 0 0 23 * * *